<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            ['id' => '1', 'name' => 'Afghanistan'],
            ['id' => '2', 'name' => 'Aland'],
            ['id' => '3', 'name' => 'Albania'],
            ['id' => '4', 'name' => 'Algeria'],
            ['id' => '5', 'name' => 'American Samoa'],
            ['id' => '6', 'name' => 'Andorra'],
            ['id' => '7', 'name' => 'Angola'],
            ['id' => '8', 'name' => 'Antarctica'],
            ['id' => '9', 'name' => 'Antigua and Barbuda'],
            ['id' => '10', 'name' => 'Argentina'],
            ['id' => '11', 'name' => 'Armenia'],
            ['id' => '12', 'name' => 'Aruba'],
            ['id' => '13', 'name' => 'Australia'],
            ['id' => '14', 'name' => 'Austria'],
            ['id' => '15', 'name' => 'Azerbaijan'],
            ['id' => '16', 'name' => 'Bahrain'],
            ['id' => '17', 'name' => 'Bangladesh'],
            ['id' => '18', 'name' => 'Barbados'],
            ['id' => '19', 'name' => 'Belarus'],
            ['id' => '20', 'name' => 'Belgium'],
            ['id' => '21', 'name' => 'Belize'],
            ['id' => '22', 'name' => 'Benin'],
            ['id' => '23', 'name' => 'Bermuda'],
            ['id' => '24', 'name' => 'Bhutan'],
            ['id' => '25', 'name' => 'Bolivia'],
            ['id' => '26', 'name' => 'Bosnia and Herzegovina'],
            ['id' => '27', 'name' => 'Botswana'],
            ['id' => '28', 'name' => 'Brazil'],
            ['id' => '29', 'name' => 'Brunei'],
            ['id' => '30', 'name' => 'Bulgaria'],
            ['id' => '31', 'name' => 'Burkina Faso'],
            ['id' => '32', 'name' => 'Burundi'],
            ['id' => '33', 'name' => 'Cambodia'],
            ['id' => '34', 'name' => 'Cameroon'],
            ['id' => '35', 'name' => 'Canada'],
            ['id' => '36', 'name' => 'Cape Verde'],
            ['id' => '37', 'name' => 'Cayman Islands'],
            ['id' => '38', 'name' => 'Central African Republic'],
            ['id' => '39', 'name' => 'Chad'],
            ['id' => '40', 'name' => 'Chile'],
            ['id' => '41', 'name' => 'China'],
            ['id' => '42', 'name' => 'Colombia'],
            ['id' => '43', 'name' => 'Comoros'],
            ['id' => '44', 'name' => 'Congo (Brazzaville)'],
            ['id' => '45', 'name' => 'Congo (Kinshasa)',],
            ['id' => '46', 'name' => 'Cook Islands'],
            ['id' => '47', 'name' => 'Costa Rica'],
            ['id' => '48', 'name' => 'Croatia'],
            ['id' => '49', 'name' => 'Cuba'],
            ['id' => '50', 'name' => 'Curacao'],
            ['id' => '51', 'name' => 'Cyprus'],
            ['id' => '52', 'name' => 'Czech Republic'],
            ['id' => '53', 'name' => 'Denmark'],
            ['id' => '54', 'name' => 'Djibouti'],
            ['id' => '55', 'name' => 'Dominica'],
            ['id' => '56', 'name' => 'Dominican Republic'],
            ['id' => '57', 'name' => 'East Timor'],
            ['id' => '58', 'name' => 'Ecuador'],
            ['id' => '59', 'name' => 'Egypt'],
            ['id' => '60', 'name' => 'El Salvador'],
            ['id' => '61', 'name' => 'Equatorial Guinea'],
            ['id' => '62', 'name' => 'Eritrea'],
            ['id' => '63', 'name' => 'Estonia'],
            ['id' => '64', 'name' => 'Ethiopia'],
            ['id' => '65', 'name' => 'Falkland Islands'],
            ['id' => '66', 'name' => 'Faroe Islands'],
            ['id' => '67', 'name' => 'Federated States of Micronesia'],
            ['id' => '68', 'name' => 'Fiji'],
            ['id' => '69', 'name' => 'Finland'],
            ['id' => '70', 'name' => 'France'],
            ['id' => '71', 'name' => 'French Polynesia'],
            ['id' => '72', 'name' => 'Gabon'],
            ['id' => '73', 'name' => 'Georgia'],
            ['id' => '74', 'name' => 'Germany'],
            ['id' => '75', 'name' => 'Ghana'],
            ['id' => '76', 'name' => 'Gibraltar'],
            ['id' => '77', 'name' => 'Greece'],
            ['id' => '78', 'name' => 'Greenland'],
            ['id' => '79', 'name' => 'Grenada'],
            ['id' => '80', 'name' => 'Guam'],
            ['id' => '81', 'name' => 'Guatemala'],
            ['id' => '82', 'name' => 'Guinea'],
            ['id' => '83', 'name' => 'Guinea Bissau'],
            ['id' => '84', 'name' => 'Guyana'],
            ['id' => '85', 'name' => 'Haiti'],
            ['id' => '86', 'name' => 'Honduras'],
            ['id' => '87', 'name' => 'Hong Kong S.A.R.'],
            ['id' => '88', 'name' => 'Hungary'],
            ['id' => '89', 'name' => 'Iceland'],
            ['id' => '90', 'name' => 'India'],
            ['id' => '91', 'name' => 'Indonesia'],
            ['id' => '92', 'name' => 'Iran'],
            ['id' => '93', 'name' => 'Iraq'],
            ['id' => '94', 'name' => 'Ireland'],
            ['id' => '95', 'name' => 'Isle of Man'],
            ['id' => '96', 'name' => 'Israel'],
            ['id' => '97', 'name' => 'Italy'],
            ['id' => '98', 'name' => 'Ivory Coast'],
            ['id' => '99', 'name' => 'Jamaica'],
            ['id' => '100', 'name' => 'Japan'],
            ['id' => '101', 'name' => 'Jordan'],
            ['id' => '102', 'name' => 'Kazakhstan'],
            ['id' => '103', 'name' => 'Kenya'],
            ['id' => '104', 'name' => 'Kiribati'],
            ['id' => '105', 'name' => 'Kosovo'],
            ['id' => '106', 'name' => 'Kuwait'],
            ['id' => '107', 'name' => 'Kyrgyzstan'],
            ['id' => '108', 'name' => 'Laos'],
            ['id' => '109', 'name' => 'Latvia'],
            ['id' => '110', 'name' => 'Lebanon'],
            ['id' => '111', 'name' => 'Lesotho'],
            ['id' => '112', 'name' => 'Liberia'],
            ['id' => '113', 'name' => 'Libya'],
            ['id' => '114', 'name' => 'Liechtenstein'],
            ['id' => '115', 'name' => 'Lithuania'],
            ['id' => '116', 'name' => 'Luxembourg'],
            ['id' => '117', 'name' => 'Macau S.A.R'],
            ['id' => '118', 'name' => 'Macedonia'],
            ['id' => '119', 'name' => 'Madagascar'],
            ['id' => '120', 'name' => 'Malawi'],
            ['id' => '121', 'name' => 'Malaysia'],
            ['id' => '122', 'name' => 'Maldives'],
            ['id' => '123', 'name' => 'Mali'],
            ['id' => '124', 'name' => 'Malta'],
            ['id' => '125', 'name' => 'Marshall Islands'],
            ['id' => '126', 'name' => 'Mauritania'],
            ['id' => '127', 'name' => 'Mauritius'],
            ['id' => '128', 'name' => 'Mexico'],
            ['id' => '129', 'name' => 'Moldova'],
            ['id' => '130', 'name' => 'Monaco'],
            ['id' => '131', 'name' => 'Mongolia'],
            ['id' => '132', 'name' => 'Montenegro'],
            ['id' => '133', 'name' => 'Morocco'],
            ['id' => '134', 'name' => 'Mozambique'],
            ['id' => '135', 'name' => 'Myanmar'],
            ['id' => '136', 'name' => 'Namibia'],
            ['id' => '137', 'name' => 'Nepal'],
            ['id' => '138', 'name' => 'Netherlands'],
            ['id' => '139', 'name' => 'New Caledonia'],
            ['id' => '140', 'name' => 'New Zealand'],
            ['id' => '141', 'name' => 'Nicaragua'],
            ['id' => '142', 'name' => 'Niger'],
            ['id' => '143', 'name' => 'Nigeria'],
            ['id' => '144', 'name' => 'North Korea'],
            ['id' => '145', 'name' => 'Northern Cyprus'],
            ['id' => '146', 'name' => 'Northern Mariana Islands'],
            ['id' => '147', 'name' => 'Norway'],
            ['id' => '148', 'name' => 'Oman'],
            ['id' => '149', 'name' => 'Pakistan'],
            ['id' => '150', 'name' => 'Palau'],
            ['id' => '151', 'name' => 'Palestine'],
            ['id' => '152', 'name' => 'Panama'],
            ['id' => '153', 'name' => 'Papua New Guinea'],
            ['id' => '154', 'name' => 'Paraguay'],
            ['id' => '155', 'name' => 'Peru'],
            ['id' => '156', 'name' => 'Philippines'],
            ['id' => '157', 'name' => 'Poland'],
            ['id' => '158', 'name' => 'Portugal'],
            ['id' => '159', 'name' => 'Puerto Rico'],
            ['id' => '160', 'name' => 'Qatar'],
            ['id' => '161', 'name' => 'Romania'],
            ['id' => '162', 'name' => 'Russia'],
            ['id' => '163', 'name' => 'Rwanda'],
            ['id' => '164', 'name' => 'Saint Kitts and Nevis'],
            ['id' => '165', 'name' => 'Saint Lucia'],
            ['id' => '166', 'name' => 'Saint Vincent and the Grenadines'],
            ['id' => '167', 'name' => 'Samoa'],
            ['id' => '168', 'name' => 'San Marino'],
            ['id' => '169', 'name' => 'Sao Tome and Principe'],
            ['id' => '170', 'name' => 'Saudi Arabia'],
            ['id' => '171', 'name' => 'Senegal'],
            ['id' => '172', 'name' => 'Serbia'],
            ['id' => '173', 'name' => 'Seychelles'],
            ['id' => '174', 'name' => 'Sierra Leone'],
            ['id' => '175', 'name' => 'Singapore'],
            ['id' => '176', 'name' => 'Slovakia'],
            ['id' => '177', 'name' => 'Slovenia'],
            ['id' => '178', 'name' => 'Solomon Islands'],
            ['id' => '179', 'name' => 'Somalia'],
            ['id' => '180', 'name' => 'Somaliland'],
            ['id' => '181', 'name' => 'South Africa'],
            ['id' => '182', 'name' => 'South Georgia and the Islands'],
            ['id' => '183', 'name' => 'South Korea'],
            ['id' => '184', 'name' => 'South Sudan'],
            ['id' => '185', 'name' => 'Spain'],
            ['id' => '186', 'name' => 'Sri Lanka'],
            ['id' => '187', 'name' => 'Sudan'],
            ['id' => '188', 'name' => 'Suriname'],
            ['id' => '189', 'name' => 'Svalbard and Jan Mayen Islands'],
            ['id' => '190', 'name' => 'Swaziland'],
            ['id' => '191', 'name' => 'Sweden'],
            ['id' => '192', 'name' => 'Switzerland'],
            ['id' => '193', 'name' => 'Syria'],
            ['id' => '194', 'name' => 'Taiwan'],
            ['id' => '195', 'name' => 'Tajikistan'],
            ['id' => '196', 'name' => 'Tanzania'],
            ['id' => '197', 'name' => 'Thailand'],
            ['id' => '198', 'name' => 'The Bahamas'],
            ['id' => '199', 'name' => 'The Gambia'],
            ['id' => '200', 'name' => 'Togo'],
            ['id' => '201', 'name' => 'Tonga'],
            ['id' => '202', 'name' => 'Trinidad and Tobago'],
            ['id' => '203', 'name' => 'Tunisia'],
            ['id' => '204', 'name' => 'Turkey'],
            ['id' => '205', 'name' => 'Turkmenistan'],
            ['id' => '206', 'name' => 'Turks and Caicos Islands'],
            ['id' => '207', 'name' => 'Tuvalu'],
            ['id' => '208', 'name' => 'Uganda'],
            ['id' => '209', 'name' => 'Ukraine'],
            ['id' => '210', 'name' => 'United Arab Emirates'],
            ['id' => '211', 'name' => 'United Kingdom'],
            ['id' => '212', 'name' => 'United States of America'],
            ['id' => '213', 'name' => 'United States Virgin Islands'],
            ['id' => '214', 'name' => 'Uruguay'],
            ['id' => '215', 'name' => 'Uzbekistan'],
            ['id' => '216', 'name' => 'Vanuatu'],
            ['id' => '217', 'name' => 'Vatican (Holy Sea)'],
            ['id' => '218', 'name' => 'Venezuela'],
            ['id' => '219', 'name' => 'Vietnam'],
            ['id' => '220', 'name' => 'Western Sahara'],
            ['id' => '221', 'name' => 'Yemen'],
            ['id' => '222', 'name' => 'Zambia'],
            ['id' => '223', 'name' => 'Zimbabwe']
        ];
        Schema::disableForeignKeyConstraints();
        Country::truncate();
        Country::insert($countries);
        Schema::enableForeignKeyConstraints();
    }
}
