<?php 
return [
	'term_of_use_en' => '<p>hhh</p>',
	'privacy_policy_en' => '<p>ddd</p>',
	'term_of_use_ar' => '<p><br></p>',
	'privacy_policy_ar' => '<p><br></p>',
	'term_of_use_tr' => '<p><br></p>',
	'privacy_policy_tr' => '<p><br></p>',
	'business_logo' => '3351619343003.png',
	'business_name' => 'name',
	'business_email' => 'email@ff.co',
	'business_phone' => '+963966423758',
	'business_facebook' => 'face',
	'business_linkedin' => 'link',
	'business_twitter' => 'twit',
	'business_instagram' => 'insta',
	'email_acc_name' => 'alaa',
	'email_acc_pass' => '45646',
	'email_acc_user' => 'alaaeddinkhudro@gmail.com',
	'email_method' => 'pop3',
	'email_ssl_tls' => 'ssl',
	'email_server_host' => 'smtp.mailtrap.io',
	'email_server_port' => '2525',
	'email_from_name' => 'alaa',
	'email_from_address' => 'alaaeddinkhudro@gmail.com',
	'email_username' => '43619908a85172',
	'email_password' => '3f78cb1156b949',
	'email_encryption' => 'tls',
	'email_mailer' => 'smtp',
];